/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    implementation(libs.org.apache.commons)

    implementation(libs.net.minestom)
    implementation(libs.org.slf4j)

    testImplementation(libs.org.junit.jupiter)
}

group = "org.example"
version = "0.0.10"
description = "toy-language"
java.sourceCompatibility = JavaVersion.VERSION_21

tasks.withType<Test> {
    useJUnitPlatform()
    systemProperty("line.separator", "\n")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
